# Generated by Django 2.2.7 on 2019-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Fcontact', models.CharField(max_length=15)),
                ('Faadhar', models.CharField(max_length=20)),
                ('Faddress1', models.CharField(max_length=100)),
                ('Faddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('Faddress3', models.CharField(blank=True, max_length=100, null=True)),
                ('Fration', models.CharField(blank=True, max_length=100, null=True)),
                ('Farogya', models.CharField(blank=True, max_length=100, null=True)),
                ('Member_1_name', models.CharField(max_length=100)),
                ('Member_1_aadhar', models.CharField(max_length=20)),
                ('Member_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Member_2_aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('Member_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Member_3_aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('Member_4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Member_4_aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('pc', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=1350, null=True)),
                ('paid', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Fcontact', models.CharField(max_length=15)),
                ('Faadhar', models.CharField(max_length=20)),
                ('Faddress1', models.CharField(max_length=100)),
                ('Faddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('Faddress3', models.CharField(blank=True, max_length=100, null=True)),
                ('Fration', models.CharField(blank=True, max_length=100, null=True)),
                ('Farogya', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=750, null=True)),
                ('pc', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'individual',
            },
        ),
    ]
