# Generated by Django 2.2.7 on 2019-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='paid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
