# Generated by Django 2.2.7 on 2019-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=20)),
                ('Fname', models.CharField(max_length=100)),
                ('Fcontact', models.CharField(max_length=15)),
                ('Faadhar', models.CharField(max_length=20)),
                ('Faddress2', models.CharField(max_length=100)),
                ('Faddress3', models.CharField(max_length=100)),
                ('Faddress1', models.CharField(max_length=100)),
                ('Fration', models.CharField(max_length=100)),
                ('Farogya', models.CharField(max_length=100)),
                ('Member_1_name', models.CharField(max_length=100)),
                ('Member_1_aadhar', models.CharField(max_length=20)),
                ('Member_2_name', models.CharField(max_length=100)),
                ('Member_2_aadhar', models.CharField(max_length=20)),
                ('Member_3_name', models.CharField(max_length=100)),
                ('Member_3_aadhar', models.CharField(max_length=20)),
                ('Member_4_name', models.CharField(max_length=100)),
                ('Member_4_aadhar', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=1350)),
                ('paid', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('Fid', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=100)),
                ('Fcontact', models.CharField(max_length=15)),
                ('Faadhar', models.CharField(max_length=20)),
                ('Faddress2', models.CharField(max_length=100)),
                ('Faddress3', models.CharField(max_length=100)),
                ('Faddress1', models.CharField(max_length=100)),
                ('Fration', models.CharField(max_length=100)),
                ('Farogya', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1350)),
                ('paid', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'individual',
            },
        ),
    ]
