# Generated by Django 2.2.7 on 2019-12-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_family_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.AlterField(
            model_name='family',
            name='Fid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='price',
            field=models.IntegerField(default=1350, editable=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='price',
            field=models.IntegerField(default=1350, editable=False),
        ),
    ]
