# Generated by Django 2.2.7 on 2019-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20191214_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='family',
            name='price',
            field=models.IntegerField(default=1350),
        ),
        migrations.AlterField(
            model_name='individual',
            name='price',
            field=models.IntegerField(default=750),
        ),
    ]
