# Generated by Django 2.2.7 on 2019-12-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20191221_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
