# Generated by Django 2.2.7 on 2019-12-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20191214_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='pc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='pc',
            field=models.IntegerField(default=0),
        ),
    ]
